FROM debian
MAINTAINER Vitaliy T

RUN \
apt-get update && apt-get upgrade -y; \
apt-get install -y  software-properties-common python-software-properties \
                    vim mc nano htop git screen curl unzip wget tmux zip supervisor
   
   
   locales, man-pages
   
   
#debconf: delaying package configuration, since apt-utils is not installed
